openapi: 3.0.0
info:
  title: 06_JOBSTER_API
  version: 1.0.0
servers:
  - url: https://temp-jobs-5klq.onrender.com
components:
  securitySchemes:
    noauthAuth:
      type: http
      scheme: noauth
    bearerAuth:
      type: http
      scheme: bearer
paths:
  /api/v1/auth/register:
    post:
      tags:
        - General
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: niko3433333
                email: youngmoney@gmail.com
                password: youngmoney
      security:
        - noauthAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/auth/login:
    post:
      tags:
        - General
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: youngmoney@gmail.com
                password: youngmoney
      security:
        - noauthAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: >-
            Bearer
            eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2N2FjMWEyZjE0Y2NmMTAxYTAzYjg4NzQiLCJuYW1lIjoiam9obmF0aGFuIiwiaWF0IjoxNzM5MzMyMTQzLCJleHAiOjE3NDE5MjQxNDN9.xb20j8Gc9jWeKLtvhe4cbRSqIPZ949tYm5W_jZkjx3A
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/jobs:
    post:
      tags:
        - General
      summary: Create a job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: google12
                position: intern222222
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    get:
      tags:
        - General
      summary: Get Users Jobs
      security:
        - bearerAuth: []
      parameters:
        - name: Authorization
          in: header
          schema:
            type: string
          example: Bearer {{accessToken}}
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /api/v1/jobs/{id}:
    get:
      tags:
        - General
      summary: Get single job
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "67ac8a872c1df21054c14bb4"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    patch:
      tags:
        - General
      summary: Update job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: google12
                position: "11111111111111"
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "67ac8a872c1df21054c14bba"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - General
      summary: Delete job
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          example: "67ac8a872c1df21054c14bba"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
